# -*- coding: utf-8 -*-
"""Correlacao_desvio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okRm318YqzSNN7W3ZzFDkH6IhT43NuWi
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import scipy as sp

dados_fill = dados.fillna(dados["Taxa_Abandono"].median())

dados = pd.read_csv("/content/AbandonoEscolar_RendaMedia_2013_2023.csv")

dados_limpo = dados.dropna()

print(dados["Taxa_Abandono"])

media_taxa = np.mean(dados_limpo["Taxa_Abandono"])
desvio_taxa = np.std(dados_limpo["Taxa_Abandono"])
coeficiente_variacao_taxa = (desvio_taxa / media_taxa) *100
print(coeficiente_variacao_taxa)



media_renda = np.mean(dados_limpo["Renda_Media"])
desvio_renda = np.std(dados_limpo["Renda_Media"])
coeficiente_variacao_renda = (desvio_renda / media_renda) *100
print(coeficiente_variacao_renda)



lista = [x for x in dados_limpo["Taxa_Abandono"] if x <= 100.0]
plt.boxplot(lista, patch_artist=True)
plt.ylim(0, 100.0)
plt.ylabel("Taxa de Abandono")
plt.title("Boxplot da Taxa de Abandono",fontsize=10)
plt.show()

dados3000 = dados[dados["Renda_Media"] <= 5500.0]
dados3000

corr = dados3000["Renda_Media"].corr(dados3000["Taxa_Abandono"])
corr

plt.boxplot(dados_limpo["Renda_Media"])
plt.ylabel("Renda Média")
plt.title("Boxplot da Renda Média", fontsize=10)
plt.savefig("boxplot_renda.png")
plt.show()

corrS = sp.stats.spearmanr(dados_limpo["Taxa_Abandono"], dados_limpo["Renda_Media"])
print(corrS)

corr = sp.stats.spearmanr(dados_fill["Taxa_Abandono"], dados_fill["Renda_Media"])
print(corr)

dados["Renda_Media"].min()

plt.scatter(dados_limpo["Renda_Media"], dados_limpo["Taxa_Abandono"], color='blue', label='Pontos')
plt.xlabel("Renda Média")
plt.ylabel("Taxa de Abandono")
plt.title("Relação entre Renda Média e Taxa de Abandono")
plt.show()



plt.scatter(dados_limpo["Taxa_Abandono"], dados_limpo["Renda_Media"], color='blue', label='Pontos')
plt.show()